exclude:
- /resources/lang/en/validation.php
- /config/app.php
- /config/auth.php
- /config/broadcasting.php
- /config/filesystems.php
- /config/database.php
- /config/cache.php
- /config/mail.php
- /config/services.php
- /config/queue.php
component_depth: 2
languages:
- php
- name: php
  production:
    exclude:
      - /tests/.*
  test:
    include:
      - /tests/.*
