exclude:
- /resources/lang/en/validation.php
- /config
- /bower_components
- /Exeptions
- /bootstrap
- /lang

component_depth: 2
languages:
- php
- name: php
  production:
    exclude:
      - /tests/.*
  test:
    include:
      - /tests/.*
