exclude:
- /resources/lang/en/validation.php
- /config/.*
- /bower_components/.*
- /Exceptions/.*
- /bootstrap/.*
- /lang/.*
- /migrations/.*

component_depth: 2
languages:
- php
- name: php
  production:
    exclude:
      - /tests/.*
  test:
    include:
      - /tests/.*
